### ISSUE TITLE
ArcBall crashes for Mac / OSX

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#109]
Observed by Colleagues from ExoMars. When changing from FreeFly to ArcBall the SW it crashes.
From SOWG feedback slack channel:
"Pro3D on OSX (Darwin 20.6.0 Darwin Kernel Version 20.6.0:): after loading sol 49 NAVCAM, changing from FreeFly to ArcBall view, crashes the view and an AARDVARK logo comes back and feezes the software. [tech-issue tag]"
Data available on ftp://PRoVi-OpenAccess@digital.joanneum.at/Mars/ExoMars/Simulations/Sim-2/PanCam/Sol-49, credentials available at VRVis

**Comment by haraldsteinlechner** [comment]
hi gerhard. thanks for the report. actually... just *not* in time, yesterday we built a new version which is currently in testing stage but not yet public. new version should arrive today officially on github.

bests, harald

**Comment by haraldsteinlechner** [comment]
the new release is ready and can be found on the releases page: https://github.com/pro3d-space/PRo3D/releases/tag/4.0.3
