### ISSUE TITLE
GeoJSON Import and Export

### ISSUE THREAD

**Issue by ThomasOrtner** [pro3d-space/PRo3D#11]
Importing and Exporting annotations as GeoJSON is crucial for interoperability with other tools used by NASA and ESA. Annotations in this format should contain geometry in x/y.z IAU format and in lon/lat/alt format. We see the following steps to address this problem

- [x] find .net or create with chiron a GeoJSON reader and writer
- [x] find a translation from Annotation to GeoJSON and vice versa
- [x] export annotations as GeoJSON
- [ ] import (foreign) GeoJSON into PRo3D and interpret as annotations
- [x] address multiple coordinate systems

**Comment by gpaar** [comment]
Moved to new issue
