### ISSUE TITLE
cm-to-submm scale: Intersection frequently fail

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#115]
For very close-range data sets extending a few cm, intersections to "PickExploreCenter" or annotate or place scale bars etc. frequently fail. e.g. use sftp://mastcam-z@dig-sftp.joanneum.at:2200/Mission/0100/0134/Job_0134_3177-110-fdr/result/Job_0134_3177-110-fdr_opc.zip.  Perhaps the selected minimum picking tolerance of 0.01 is still too small for that scene?
![image](https://user-images.githubusercontent.com/65888251/136468154-1b4f05f6-ccdd-4054-99f0-9de6d1348f1d.png)
![ZCAM-0134-ZCAM03177-L0R0-FDR-PRo3D-ScaleBars](https://user-images.githubusercontent.com/65888251/136468174-354f0cfc-6671-453f-9369-a4e480b8d04f.JPG)

**Comment by haraldsteinlechner** [comment]
this appeared again, and was filed as a duplicate issue. I'm closing this one in favor of the newest one which gets higher priority and is currently handled: https://github.com/pro3d-space/PRo3D/issues/240
