### ISSUE TITLE
Sequenced Bookmarks

### ISSUE THREAD

**Issue by ThomasOrtner** [pro3d-space/PRo3D#12]
Bookmarks are a valuable instrument to tell stories in the 3D Martian environment, but currently they are inconvenient to use. For improved usability and as baseline for academic work we need a GUI that allows the reordering of bookmarks and convenient step-through mechanisms. Further, we want to couple the visibility of surfaces and annotations with a bookmarks as well as the navigation mode. 

- [x]  reorder bookmarks in the bookmarks tab (grouping is probably unnecessary)
- [x]  have an interaction to quickly switch through bookmarks, show bookmark name somewhere on transition
- [x] save surface and annotation visibility with bookmark
- [ ] take navigation mode into account
- [x] batch rendering of camera flight defined by bookmark sequence (via JSON export) 

Additional tasks based on user feedback:
- [x] bug: delay sometimes not used when replaying sequence
- [x] bug: delay under 1.0 results in no delay
- [x] let user set camera pause on bookmark (delay) for each bookmark separately not globally 
- [x] user defined path
- [x] user defined FPS
- [x] render identical images according to FPS when camera pauses on bookmark
- [x] include bookmark names in image file names
- [x] animation duration for each bookmark instead of one global value
- [x] allow editing of json file before generating

**Comment by LauraFritz14** [comment]
**Branch**: develop/features/sequencedBookmarks
**Commit**: 7c514f7
**Testdata**: Surface: file://euclid.vrvis.lan/InOut/PRo3D/Job-MCZ-Pano-Sol3_opc.zip
scene, stone: Z:\projects\11-ExoMars\data\_SCENES\SequencedBookmarks

![SB](https://user-images.githubusercontent.com/24911426/124594372-0100fa00-de60-11eb-8c07-75dc928e7321.png)

To **add a new bookmark** press the button (A).
The new bookmark is added to the SequencedBookmarks list (right). Under the bookmark's name is a little menu (B):
- FlyTo: triggers a FlyTo animation
- Remove: removes the bookmark bar from the list
- Move up: moves the bookmark one position up
- Move down: moves the bookmark one position down

The selected bookmark turns the color to green. Then you can see the bookmark's properties in the **Properties panel**:
- Change Name: you can change the name in the listing (press enter)
- the camera parameter

**Animation** (C):
- Backward: FlyTo the previous item in the listing, starting from the selected (green) one
- Play: starts the animation. FlyTo from bookmark to bookmark in the order of the listing, beginning with the first one.
- Pause: pause the animation. Press "Play" to continue.
- Stop: stops the animation. After "Stop", "Play" starts the animation from the beginning.
- Forward: FlyTo the next item in the listing, starting from the selected (green) one

**Comment by chris-traxler** [comment]
All features described above were tested successfully. User interaction is intuitive.

**Comment by LauraFritz14** [comment]
**Commit**: a26b97e
**New Testscene**: Z:\projects\11-ExoMars\data_SCENES\SequencedBookmarks\sequencedBookmarksWithDelay.pro3d(.ann)
**NOTE: the old testscene isnt working in this commit!!**

![animation](https://user-images.githubusercontent.com/24911426/125802984-ca737efd-d72a-4b79-8b6b-b6f7188ca253.png)

- Duration: the duration of the flight between two bookmarks
- Delay: the duration between the start of an animation and the start of the next animation
For example: fast flight (=small duration value) and long break at the bookmark position (=high delay)

**Comment by chris-traxler** [comment]
Changing duration and delay works very well. What I don't understand is, why the sliders influence each other (see video).

https://user-images.githubusercontent.com/5574563/125913645-581fc9ab-2b4d-43c3-979e-3e78a0457fca.mp4

**Comment by LauraFritz14** [comment]
![img](https://user-images.githubusercontent.com/24911426/125928965-be96cefc-1ec1-465e-b9a9-ea82a1ae384b.png)

"delay" is the time between the start of one animation (BM1) and the next animation (BM2) (= flight time + break at the next BM).
"duration" is the flight time.
So "delay" is never smaller than "duration". The difference between "duration" and "delay" is the time the animation stays at BM2.
Description of the sketch above: 

- the animation starts at BM1 (delay starts)
- flyTo for "duration" time at BM2
- stays for "delay" time - "duration" time at BM2
- starts animation at BM2 when "delay" time ends

**Comment by haraldsteinlechner** [comment]
@RebeccaNowak shall we close this one?
