### ISSUE TITLE
Integration of Mars2020 rover traverse

### ISSUE THREAD

**Issue by ThomasOrtner** [pro3d-space/PRo3D#127]
Import and visualization of [rover traverse](https://mars.nasa.gov/mmgis-maps/M20/Layers/json/M20_waypoints.json). Currently, the M20_waypoints.json in GeoJSON Format cannot be parsed. It fails with values that are not marked as string (0.0 instead of "0.0"). Currently, the M20_waypoints.json is automatically deployd into the appdata pro3d folder. This should be replaced by an import dialog. Only one traverse needs to be active at one time, although it might be useful for other projects to handle multiple traverses.

- [x] adapt GeoJSON parser to read numeric values
- [x] add file dialog to import traverses in the form of the specified GeoJSON M20_waypoints.json
- [x] add datamodel and GUI to maintain multiple traverses

**Comment by LauraFritz14** [comment]
**Branch:** features/m2020traverseUpdate
**Testdata:** 
- Surface: Z:\projects\16-Mastcam-Z\data\Jezero1.rar
- Traverses: Z:\projects\16-Mastcam-Z\data\Traverse

![Traverses](https://user-images.githubusercontent.com/24911426/156843474-cf20f63f-82cd-4bdb-8a7a-9e256448158c.png)

To load a new traverse select Extras -> Import Traverse

**Comment by ThomasOrtner** [comment]
looks great, can't wait to look at the current traverse!
