### ISSUE TITLE
Error and Crash on loading PLY

### ISSUE THREAD

**Issue by RebeccaNowak** [pro3d-space/PRo3D#133]
on branch develop
Data:
\\euclid\InOut\PRo3D\DidymainPly

 7: ERROR
 7:   [Client] 2: rendering faulted with System.Exception: [GL] could not get uniform: { ufName = "FootprintModelViewProj"
 7:     ufType = Mat (4,4,Float 32)
 7:     ufOffset = 0 }
 7:      at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
 7:      at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in E:\A\_work\130\s\src\fsharp\FSharp.Core\local.fs:line 249
 7:      at Aardvark.Rendering.GL.UniformBufferManager.CreateUniformBuffer(GLSLUniformBuffer block, Scope scope, IUniformProvider u, SymbolDict`1 additional)
 7:      at Aardvark.Rendering.GL.PreparedPipelineStateModule.mapping@1-1(ResourceManager x, IUniformProvider uniforms, Scope scope, String tupledArg0, GLSLUniformBuffer tupledArg1)
 7:      at Aardvark.Rendering.GL.PreparedPipelineStateModule.ResourceManager.CreateUniformBuffers(ResourceManager x, InterfaceSlots iface, IUniformProvider uniforms, Scope scope)
 7:      at Aardvark.Rendering.GL.PreparedPipelineStateModule.ofRenderObject(IFramebufferSignature fboSignature, ResourceManager x, RenderObject rj)
 7:      at Aardvark.Rendering.GL.PreparedCommandModule.ofRenderObject@1207(Boolean owned, IFramebufferSignature fboSignature, ResourceManager x, IRenderObject o)
 7:      at Aardvark.Rendering.GL.RenderTasks.preparedObjects@438-3.Invoke(IRenderObject x)
 7:      at FSharp.Data.Adaptive.Cache`2.Invoke(T1 v)
 7:      at FSharp.Data.Adaptive.AdaptiveHashSetImplementation.DeltaMapping@416.Invoke(SetOperation`1 d)
 7:      at <StartupCode$FSharp-Data-Adaptive>.$HashSetDelta.Map@87.Invoke(T k, Int32 v)
 7:      at FSharp.Data.Adaptive.HashImplementation.MapNode.iter[K,V](FSharpFunc`3 action, SetNode`1 node)
 7:      at FSharp.Data.Adaptive.FSharpHashSetDelta`1.Map[T2](FSharpFunc`2 mapping)
 7:      at FSharp.Data.Adaptive.AdaptiveHashSetImplementation.DeltaMapping@416-1.Invoke(FSharpHashSetDelta`1 set)
 7:      at <StartupCode$FSharp-Data-Adaptive>.$History.arg10@488-6[State,Delta,ViewState,ViewDelta](HistoryReader`4 x, AdaptiveToken token)
 7:      at FSharp.Data.Traceable.HistoryReader`4.GetChanges(AdaptiveToken token)
 7:      at FSharp.Data.Traceable.HistoryReader`4.FSharp.Data.Traceable.IOpReader<'ViewDelta>.GetChanges(AdaptiveToken c)
 7:      at FSharp.Data.Traceable.History`2.Update(AdaptiveToken self)
 7:      at <StartupCode$FSharp-Data-Adaptive>.$History.arg10@378-4[State,Delta](History`2 x, RelevantNode`2 old, State oldState, AdaptiveToken token)
 7:      at FSharp.Data.Traceable.History`2.Read(AdaptiveToken token, RelevantNode`2 old, State oldState)
 7:      at <StartupCode$FSharp-Data-Adaptive>.$History.arg10@455-5[State,Delta](HistoryReader`2 x, AdaptiveToken token)
 7:      at FSharp.Data.Traceable.HistoryReader`2.GetChanges(AdaptiveToken token)
 7:      at FSharp.Data.Traceable.HistoryReader`2.FSharp.Data.Traceable.IOpReader<'Delta>.GetChanges(AdaptiveToken c)
 7:      at Aardvark.Rendering.GL.RenderTasks.RenderTask.ProcessDeltas(AdaptiveToken token, RenderToken t)
 7:      at Aardvark.Rendering.GL.RenderTasks.AbstractOpenGlRenderTask.Perform(AdaptiveToken token, RenderToken t, OutputDescription desc, IQuery queries)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.Run@134-3.Invoke(AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.arg10@132-6(AbstractRenderTask x, RenderToken t, OutputDescription out, IQuery queries, AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.action@1-42(AbstractRenderTask x, AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries, Unit _arg1)
 7:      at Aardvark.Rendering.AbstractRenderTask.Run(AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries)
 7:      at Aardvark.Rendering.AbstractRenderTask.Aardvark.Rendering.IRenderTask.Run(AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries)
 7:      at <StartupCode$Aardvark-UI>.$Core.scene@1163-7.Perform(AdaptiveToken t, RenderToken rt, OutputDescription o, IQuery q)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.Run@134-3.Invoke(AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.arg10@132-6(AbstractRenderTask x, RenderToken t, OutputDescription out, IQuery queries, AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.action@1-42(AbstractRenderTask x, AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries, Unit _arg1)
 7:      at Aardvark.Rendering.AbstractRenderTask.Run(AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries)
 7:      at Aardvark.Rendering.AbstractRenderTask.Aardvark.Rendering.IRenderTask.Run(AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.Run@134-3.Invoke(AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.arg10@132-6(AbstractRenderTask x, RenderToken t, OutputDescription out, IQuery queries, AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.action@1-42(AbstractRenderTask x, AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries, Unit _arg1)
 7:      at Aardvark.Rendering.AbstractRenderTask.Run(AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries)
 7:      at Aardvark.Rendering.AbstractRenderTask.Aardvark.Rendering.IRenderTask.Run(AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries)
 7:      at Aardvark.Rendering.SequentialRenderTask.Perform(AdaptiveToken token, RenderToken rt, OutputDescription output, IQuery queries)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.Run@134-3.Invoke(AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.arg10@132-6(AbstractRenderTask x, RenderToken t, OutputDescription out, IQuery queries, AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Rendering>.$AbstractRenderTask.action@1-42(AbstractRenderTask x, AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries, Unit _arg1)
 7:      at Aardvark.Rendering.AbstractRenderTask.Run(AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries)
 7:      at Aardvark.Rendering.AbstractRenderTask.Aardvark.Rendering.IRenderTask.Run(AdaptiveToken token, RenderToken t, OutputDescription out, IQuery queries)
 7:      at <StartupCode$Aardvark-Service>.$Server.arg10@789(ClientRenderTask x, ClientState state, ClientInfo info, IRenderTask task, ConcreteScene scene, FSharpRef`1 target, AdaptiveToken token)
 7:      at <StartupCode$Aardvark-Service>.$Server.action@1-2(ClientRenderTask x, AdaptiveToken token, ClientState state, ClientInfo info, IRenderTask task, ConcreteScene scene, ChangeableValue`1 clearColor, FSharpRef`1 t, FSharpRef`1 target, Unit unitVar0)
 7:      at Aardvark.Service.ClientRenderTask.Run(AdaptiveToken token, ClientInfo info, ClientState state)
 7:      at <StartupCode$Aardvark-Service>.$Server.arg10@1802-1(Client this, V2i size, C4b background, AdaptiveToken token) (stopping)

**Comment by haraldsteinlechner** [comment]
thanks, this is actually a regression introduced by viewplanner revive. my suggestion: apply uniform as m44d.identity (surfaces need this uniform even when there is no footprint)
