### ISSUE TITLE
Offline Rendering Problems

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#149]
Offline rendering causes incorrect display of:

- [ ] Annotations (scale, etc.)
- [ ] Coordinate system
- [ ] Scale bars

The correct rendering priority is not considered.

This might be solved by merging with version from HERA or Mars-DL mainly developed by @RebeccaNowak.

[Taken from @gpaar's minutes from the meeting on Feb. 11th, 2022.]

**Comment by gpaar** [comment]
forgot to close?
