### ISSUE TITLE
Printing Point Coordinates and Bookmarkmarks Locations to console

### ISSUE THREAD

**Issue by ThomasOrtner** [pro3d-space/PRo3D#15]
Coordinate Printing functionality has been lost during the move to PRo3D v3. Also increase floating point digits of overlay to degrees showing cm resolution

- [x] print point coordinates
- [x] print bookmarks coordinates
- [x] increase lon lat overlay digits

**Comment by ThomasOrtner** [comment]
Hey @LauraFritz14 , the third task is yours ;)

**Comment by LauraFritz14** [comment]
you find the third task in:
Branch: develop/features/mastcamZ1
Commit c83f4ea
