### ISSUE TITLE
Annotation LODs

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#150]
Show or hide annotations depending on distance from viewpoint. Task separation:

- [ ] Define near and far clipping plane for annotations in UI
- [ ] Enable or disable annotation clipping in UI

The fancy version would be smart LODs for annotations, which consider the hierarchy of demarkations. Thicker poly-lines marking contacts between main stratigraphic layers remain visible from a larger distance, while thin lines marking for example cross beddings are only visible from closer ranges.  

[Taken from @gpaar's minutes from the meeting on Feb. 11th, 2022.]

**Comment by gpaar** [comment]
Redundant to [Annotations B](https://github.com/pro3d-space/PRo3D/issues/298)
