### ISSUE TITLE
Disturbing rotation after navigation to bookmarks

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#158]
When flying to a bookmark, the system often is in a condition where it jumps 180° after reaching it. This effect may be avoided when changing FreeFly to ArcBall or vice versa, or picking another rotation center. 

Solution: Make sure that bookmarks consistently define their navigation mode (FreeFly, ArcBall).

[Taken from @gpaar's minutes from the meeting on Feb. 11th, 2022.]

**Comment by gpaar** [comment]
Redundant to newly identified issues
