### ISSUE TITLE
Navigation Improvements

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#168]
Navigation should be improved in the following way:

- [ ] Option to keep the horizon always horizontal
- [ ] Adjust left/right and up/down movements with keyboard or UI controls in arbitrary granulation
- [ ] Adjust azimuth with keyboard or UI controls in arbitrary granulation
- [ ] Provide an orbital view (might be transferred to a separate issue) 

[Taken from @gpaar's minutes from the meeting on Feb. 11th, 2022.]

**Comment by gpaar** [comment]
Redundant with other new items
