### ISSUE TITLE
View Planner placed rovers not recorded in .pro3d and/or annotation file

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#179]
Any placed rovers and other related settings are lost upon next PRo3D launch even if scene is saved.
As a "side error": The "show footprint" flag doesn't have any effect, same with the "export footprint" and "show footprint folder"

**Comment by gpaar** [comment]
As a "side error": The "show footprint" flag doesn't have any effect, same with the "export footprint" and "show footprint folder"

**Comment by LauraFritz14** [comment]
pro3d version 4.10.3
