### ISSUE TITLE
obj import with large coordinates compensation

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#186]
obj files in IAU Mars coordinates are a regular use case e.g. from long baseline stereo. Currently they are taken over as-is which results in artefacts due to the large coordinate values (10e+7). It would be very helpful if the coordinates are analyzed upon load, and the first appearing coordinate or some statistically obtained values are taken to be subtracted, and the same value be added as an xyz transform upon display.
Currently even a workaround is not possible, as PRo3D only allows for manual ENH transform. Alternatively, if an xyz transform is available this could act as temporary workaround, which would mean the .obj file needs to be patched with subtracting the offsets before load.

**Comment by AndrewAnnex** [comment]
there could be an option to normalize the mesh during import (subtract average x, y, z), but also agree a panel that allows you to adjust the xyz offset would be helpful. Additional features like scale transformation would be helpful as well

**Comment by gpaar** [comment]
Workaround currently: Apply the offset by modifying outside (e.g. Cloud Compare) and re-apply the shift for the very surface. Disadvantage: Cumbersome and one has to keep within "None" coordinate system, Example of success of this workaround: https://www.youtube.com/watch?v=-z1KySwtnuU

**Comment by LauraFritz14** [comment]
fixed in version 4.10.2
