### ISSUE TITLE
add macos/linux binaries to prerelease builds

### ISSUE THREAD

**Issue by AndrewAnnex** [pro3d-space/PRo3D#194]

**Comment by haraldsteinlechner** [comment]
on it (via github ci)

**Comment by haraldsteinlechner** [comment]
@chris-traxler just tested the CI mac build on his macbook and it worked. https://github.com/pro3d-space/PRo3D/releases/tag/v4.8.2

@AndrewAnnex  could you test the mac build as well?

**Comment by AndrewAnnex** [comment]
@haraldsteinlechner it seems to work for me on macos, I had a OPC file/folder that seemed to be faulty which almost made me think it was broken on macos and windows but I just figured out a different one worked on both platforms.

**Comment by haraldsteinlechner** [comment]
this issue is also asking for linux builds. Linux builds can be made as soon as the CooTrafo is built on the CI. This would be a https://github.com/DaKup/PRo3D-Extensions/issues/5 dependency. Hope we can tackle this one soon.
