### ISSUE TITLE
make sampleCount configurable, add additional configurable samplingSpacing option

### ISSUE THREAD

**Issue by AndrewAnnex** [pro3d-space/PRo3D#203]
relates to #185 

The sampleCount parameter is currently set to 100 by default. This means that regardless of the distance between points, both the sky and viewpoint projection modes only interpolate 100 points between vertices. This is undesirable as it could result in most of the data points used in a strike dip measurement to be interpolated above or below the available resolution by a potentially significant amount. This could result in numerical instabilities in regressions or ignore available data needlessly. 

To mitigate this I propose a two step solution:
1. Make the sampleCount a user configurable value within the UI (wherever apporpriate) allowing users to control the behavior a little more closely. Ideally it would just update the value so subsequent polylines/strikedip measurements can be made without modifying older annotations

2.  Add a user configurable "sampleSpacing" option that instead specifies the linear spacing between interpolated points between two vertices. I think this would need to be tied to the coordinate system of the OPC models, if for example the model coordinates are in meters I would expect to set the sample spacing to a floating point value such as 0.01 to specify that I want points interpolated every centimeter between vertices. If this value is set it should be used rather than the direct sampleCount value.

**Comment by ThomasOrtner** [comment]
first iteration GUI
![image](https://user-images.githubusercontent.com/21270851/186723113-fdb55701-0861-4427-be73-ba291bc67c42.png)
numeric control determines the amount while a drop down determines the unit (km, m, cm, mm)

**Comment by AndrewAnnex** [comment]
@ThomasOrtner closing this issue
