### ISSUE TITLE
no annotations on OPCs with higher resolution

### ISSUE THREAD

**Issue by AndreasBechtold** [pro3d-space/PRo3D#208]
When using an OPC that was processed with a better resolution (MCZ_110mm-C-F), it is not possible to draw annotations or pick the explore center. If the picking tolerance is set to 0.01 it occasionally works.

**Comment by haraldsteinlechner** [comment]
this appeared again, and was filed as a duplicate issue. I'm closing this one in favor of the newest one which gets higher priority and is currently handled: https://github.com/pro3d-space/PRo3D/issues/240
