### ISSUE TITLE
unable to build current develop branch, wavefront could not be downloaded

### ISSUE THREAD

**Issue by AndrewAnnex** [pro3d-space/PRo3D#227]
running build.sh on macos big sur causes the following issue:

```
Paket failed with
-> Could not download Aardvark.Data.Wavefront 5.2.1.
-> Couldn't get package details for package Aardvark.Data.Wavefront 5.2.1 on https://vrvis.myget.org/F/aardvark/api/v3/index.json.
-> Could not retrieve data from 'https://vrvis.myget.org/F/aardvark/FindPackagesById()?semVerLevel=2.0.0&id='Aardvark.Data.Wavefront''
-> RequestFailedException: Request to 'https://vrvis.myget.org/F/aardvark/FindPackagesById()?semVerLevel=2.0.0&id='Aardvark.Data.Wavefront'' failed with: 401 Unauthorized — <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Unauthorized</string>
```

**Comment by AndrewAnnex** [comment]
the ability to build branches on macos is a critical issue, as it prevents timely testing and feedback of feature branches by external users

**Comment by haraldsteinlechner** [comment]
thanks @AndrewAnnex. Indeed it seems a non-public nuget feed was added recently. Also, currently the CI builds are disabled. I enabled them again, see https://github.com/pro3d-space/PRo3D/issues/228 - so continuous mac builds is of course the plan!

@LauraFritz14 could you please consult @luithefirst @hyazinthh and move the wavefront package into a public feed accordingly (if not possible, wavefront support cannot be in pro3d)

**Comment by hyazinthh** [comment]
Aardvark.Data.Wavefront has been made public some time ago, you need to update to 5.2.4 or 5.2.5.

https://www.nuget.org/packages/Aardvark.Data.Wavefront

**Comment by LauraFritz14** [comment]
I'm sorry, thats my fault. I forgot to change this!

**Comment by haraldsteinlechner** [comment]
oh cool, glad all is set. thanks a lot @LauraFritz14

**Comment by haraldsteinlechner** [comment]
@LauraFritz14  your fix is in a bug branch or something, is this branch ready now or soon? because i would like to have your fix in develop branch to check the CI action (e.g. for autodeploy)

**Comment by LauraFritz14** [comment]
@haraldsteinlechner this branch is ready. I changed the paket.dependencies and paket.lock files to get the correct path to Aardvark.Data.Wavefront

**Comment by haraldsteinlechner** [comment]
ok, i'm a bit detached in my off-time currently, but if you think, you can merge to develop, and i will do the rest to make a test deployment

**Comment by haraldsteinlechner** [comment]
@LauraFritz14 yes it worked, the build is back for windows and osx: https://github.com/pro3d-space/PRo3D/runs/7997008245?check_suite_focus=true

i will trigger a test deployment on the CI and we will see

**Comment by haraldsteinlechner** [comment]
andrew, just to let you know, by pulling in this package, we pulled in other packages transitively (classic), which makes problems at runtime. so no need to retry for now :(

**Comment by AndrewAnnex** [comment]
@haraldsteinlechner okay good to see this getting worked on

**Comment by haraldsteinlechner** [comment]
so there is a lot to tell here - a lot of code got merged now, also lurking features from before my vacation time ;) it looks good now I think.

- for deployment we now use electron (which provides signing, installers etc), the latest build released automatically from autorelease branch works fine. this involves splash screen, output log window and the build process. for this we needed to switch to dotnet 6 for the build script support. unfortunately the apps itself are still dotnet 5, but this should be easy and is outlined here: https://github.com/pro3d-space/PRo3D/issues/232
- for development, everything can be used as-is
- generally there is no different code paths for Mac or Win in the deployment / development. Yet there is some work todo to build also JR libraries in the CI...

The release is not official yet, so please @ThomasOrtner @LauraFritz14 @RebeccaNowak please check develop as well as the automatically deployed release found on the release page.

cheers, Harald

**Comment by haraldsteinlechner** [comment]
current develop branch as well as the newest release should fix the mentioned problems (https://github.com/pro3d-space/PRo3D/releases/tag/v4.9.5)
Please note that we switched fully to .net 6 which makes .net 5 sdk unnecessary. Anyhow, also the path's changed. Instead of running `dotnet bin/Release/net5.0/PRo3D.Viewer.dll` use `dotnet bin/Release/net6.0/PRo3D.Viewer.dll". When using `dotnet run --project...` nothing changes.
