### ISSUE TITLE
Last frame of batch rendering sequences not correct

### ISSUE THREAD

**Issue by RebeccaNowak** [pro3d-space/PRo3D#243]
The last frame of each sequence in batch rendering with sequenced bookmarks is slightly rotated or translated.

**Comment by RebeccaNowak** [comment]
This problem does not seem to occur anymore, please check @gpaar

**Comment by haraldsteinlechner** [comment]
@RebeccaNowak just one point to clarify: is this running in the new animation system? If not, it is clear that it could happen due to wrong interpolation at the end of each animation segment

**Comment by RebeccaNowak** [comment]
Batch rendering is not running with the new animation system, and using linear interpolation for the camera
