### ISSUE TITLE
Locate Surfaces shall apply to all sequenced bookmarks of a scene

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#244]
Upon transfer of a data set (.pro3d, .ann, surfaces) to another machine and the application of "Extras-Locate Surfaces", the surfaces aren't found in sequenced bookmars, as the paths seem to be separately stored and not being updated. 
A workaround with selecting each SB manually, doing a "Locate Surfaces" and then applying the status to the respective SB works.
It is suggested that the path names in each SB are being updated when "Locate Surfaces" is executed.

**Comment by gpaar** [comment]
Further, global settings shall remain valid and undergo a warning if changed upon sequence formation. 
As a first case, I came across the fact that for some reason the coordinate system changed between Mars and None between different bookmarks. This must not be the case and causes confusion, as e.g. transforming surfaces reacts differently under different coordinate systems. It is recommended to warn the user at least.

**Comment by RebeccaNowak** [comment]
I will split this issue into two because one is a bugfix and one is a change to the structure of sequenced bookmarks.

**Comment by RebeccaNowak** [comment]
The issue with global settings in Sequenced Bookmarks is now Issue #371

**Comment by RebeccaNowak** [comment]
currently importPath is set but not opcPaths in changeImportDirectories
Example: OPC moved from folder tmp to tmp2. When saving the scene after locating surfaces "importPath" will be "D:\\Data\\PRo3D\\tmp2\\StereoMosaic", but  "opcPaths" will still be ["D:\\Data\\PRo3D\\tmp\\StereoMosaic\\StereoMosaic_000_000"]
to be consistent I will update opcPaths as well
