### ISSUE TITLE
Adapt 'Locate surfaces' for obj files

### ISSUE THREAD

**Issue by sophie-sudoku** [pro3d-space/PRo3D#256]
**Problem**
At the moment .opc and .obj files are treated differently: 
Both can be referenced with absolute paths in the .pro3d file, but an invalid .opc file is ignored while an invalid .obj file throws an error and harms the scene-loading-process.  The 'locate surfaces' (action = ChangeImportDirectories) which updates the prefix of an import seems to be only applicable to .opc files.

**Solution**
It would be nice if .obj files are treated the same way as .obj files

**Comment by haraldsteinlechner** [comment]
@LauraFritz14 what are your thoughts on this? i think you cleaned up at least the rendering and update code for objs vs opcs. Is this an easy one?

**Comment by LauraFritz14** [comment]
pro3d version 4.10.3
