### ISSUE TITLE
Source Image Footprints

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#26]
Read in and display orientation information and footprints for all available source images visible from the current viewpoint. For that an imagery database is required. The database is queried with geo-coordinates from the viewing frustrum. Task separation:

- [ ] Integrated and debug Dominik Scholz prototype 
 
[Requirement P3D-I001](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=53:53)

**Comment by gpaar** [comment]
Redundant to 27
