### ISSUE TITLE
Ignore unused entries in traverse json

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#263]
From beginning 12/2022 the M2020 json contains more entries (apparently information about localization image files). Those shall be ignored and not cause an unrecoverable error
![image](https://user-images.githubusercontent.com/65888251/205450675-0bf00fb2-27ce-4a0e-9044-1c4df2379e25.png)
[M20_waypoints.zip](https://github.com/pro3d-space/PRo3D/files/10146888/M20_waypoints.zip)

**Comment by haraldsteinlechner** [comment]
Actually here the entry is missing the tilt property. I'm reworking the error handling approach here...
![image](https://user-images.githubusercontent.com/513281/207633009-181dcc97-f6bf-4bd6-9473-6e952fd35ea9.png)

**Comment by AndrewAnnex** [comment]
all properties that are not used by pro3d should either be removed from being parsed or should use a get-or-else with a default value or None.

**Comment by haraldsteinlechner** [comment]
Yes, i prepared for this. Acutally i just rewrote the interpretation of the json parsed values to be flexible in this regard.
Current state is that, you get pretty precise error messages, *and* robustness towards parse errors.
It looks like this now:
```
 8: WARNING: [Traverse] could not parse or interpret feature 206 in the feature list.

[Traverse] the detailled error is: PropertyNotFound ("tilt",
   { geometry =
      Point
        (ThreeDim [77.40143724515434, 18.4516192349635, -2523.9215532294925])
     bbox = None
     properties =
      map
        [("RMC", String "30_2224"); ("drive", Number 2224M);
         ("easting", Number 4351713.961164923M);
         ("elev_geoid", Number -2523.9215532294925M);
         ("lat", Number 18.4516192349635M); ("lon", Number 77.40143724515434M);
         ("northing", Number 1093714.1489676803M);
         ("pitch", Number 12.707028547054488M);
         ("roll", Number -3.3678433175221385M); ...] })
[Traverse] we simply skip this one...
```

The errors are described by this union type:
 ```
    type TraverseParseError =
       | PropertyNotFound         of propertyName : string * feature : GeoJsonFeature
       | PropertyHasWrongType     of propertyName : string * feature : GeoJsonFeature * expected : string * got : string * str : string
       | GeometryTypeNotSupported of geometryType : string
       
```

I'm not that involved in the traverse stuff so. From what i can see roll pitch yaw and the location are non-optional, the rest is - is that right?

**Comment by haraldsteinlechner** [comment]
tilt is now optional. see https://github.com/pro3d-space/PRo3D/commit/2e0bfd857bdf18b031219865e164f205977434b1#diff-ce8bc7580ea43174b1c069cccc75891cf6509bca7500a034afbc0a258b8366fbR258

**Comment by AndrewAnnex** [comment]
@haraldsteinlechner my understanding is that is the case but I haven't looked into pro3d's code to see which attributes are actually ever accessed.

**Comment by haraldsteinlechner** [comment]
i looked it up, yes tilt is unused -- roll-pitch-yaw is used to compute the orientation. the PR is basically ready. @ThomasOrtner please have a look at the PR.

**Comment by gpaar** [comment]
Setting as from 2023-02-27 is mature enough for Mars 2020 and MSL
