### ISSUE TITLE
Broken Picking on OBJ Surfaces

### ISSUE THREAD

**Issue by ThomasOrtner** [pro3d-space/PRo3D#264]
OBJs can be imported but picking / annotations do not work. Some reports indicate a problem with absolute paths as found by @sophie-sudoku 

![image](https://user-images.githubusercontent.com/21270851/205885078-5a0e8936-5b8b-42b0-8a93-c90c990a3977.png)

Oak was using  4.10.1 and 4.3, on a Mac and a Windows computer.

**Comment by ThomasOrtner** [comment]
![20221207_PRo3DPickingIssues](https://user-images.githubusercontent.com/21270851/206135390-667e7ad6-02d8-4b7b-9a68-fcf72e59f9ff.png)


Current state in branch `bugs/ObjWithoutTexture`: kdTrees can be loaded, picking still has strange behavior either a pick

*  just works,
* does not return a point 
* or returns a wrong point

**Comment by haraldsteinlechner** [comment]
thanks for the analysis. is the code still ignoring the primitive topology?

**Comment by haraldsteinlechner** [comment]
this one should be the fix, right? https://github.com/pro3d-space/PRo3D/pull/265

**Comment by haraldsteinlechner** [comment]
Testet with exactly this obj and the latest release. Is fixed, thanks @LauraFritz14
