### ISSUE TITLE
.obj with more than one texture files display incorrectly

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#274]
See https://discord.com/channels/500307805769695243/648826940689743873/1057487471031615489
Source file, e.g., https://sketchfab.com/3d-models/m2020-zcam-kodiak-delta-remnant-sol-copy-cb8a890bdf4d4f36aa6bc28f1293be96

**Comment by haraldsteinlechner** [comment]
should be fixed in  (already in 4.11.0-prerelease4)
