### ISSUE TITLE
Selected Data Export

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#30]
Export data of a region of interest. Additional selection should be possible with a line, box, sphere and an ellipse. Data to be exported are point clouds and measurements & annotations as shape files. In the first step, the current selection which works on the visibility state, is sufficient. Task separation:

- [ ] Additional surface selection tools
- [ ] Point cloud extraction and export
- [ ] Measurement and annotation extraction and export as shape file

[Requirement P3D-E001](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=65:65)

**Comment by gpaar** [comment]
Deprecated
