### ISSUE TITLE
Scale bars and text are not displayed in the Instrument View

### ISSUE THREAD

**Issue by AndreasBechtold** [pro3d-space/PRo3D#330]
When using the Viewplanner, annotations like lines and polygons are displayed in the "Instrument View" window (and the "Instrument View" screenshots), but scale bars and text is not. Scale bars in particular would be very important for assessing possible targets when using the camera zoom.

**Comment by haraldsteinlechner** [comment]
@LauraFritz14 is there some code duplication which could be resolved easily?
