### ISSUE TITLE
Spherical and cylindric projection

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#353]
To simulate mosaics and to be able to display (& hi-res screenshot) a full 360° view, the switching to cylindric and spherical projection would be helpful. The Fulcrum settings would then switch to the angular portion seen on the screen.

**Comment by gpaar** [comment]
See the M2020 Camera SIS https://pds-geosciences.wustl.edu/m2020/urn-nasa-pds-mars2020_mission/document_camera/Mars2020_Camera_SIS.pdf  Page 156

**Comment by chris-traxler** [comment]
Obsolete
