### ISSUE TITLE
Viewplan minimum value not updated

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#361]
Modifying the minimum value of the distance coloring does not gain any effect. It always stays 
![image](https://github.com/pro3d-space/PRo3D/assets/65888251/f2070b44-15d4-461d-b88c-58dc8051b4cb)
at the first ever defined value.

**Comment by LauraFritz14** [comment]
update: max of Colors minDepth NumericInput is 100.0. 
todo: increase minDepth max to max of maxDepth (10 000.0)

**Comment by LauraFritz14** [comment]
included in merge #362
