### ISSUE TITLE
Define which global settings should be saved with sequenced bookmarks

### ISSUE THREAD

**Issue by RebeccaNowak** [pro3d-space/PRo3D#371]
gpaar

> Global settings shall remain valid and undergo a warning if changed upon sequence formation.
> As a first case, I came across the fact that for some reason the coordinate system changed between Mars and None between different bookmarks. This must not be the case and causes confusion, as e.g. transforming surfaces reacts differently under different coordinate systems. It is recommended to warn the user at least.

- [x] determine which settings should be removed or given warnings
- [x] implement changes in a backward-compatible way

**Comment by RebeccaNowak** [comment]
Currently, the whole Reference System is saved with sequenced bookmarks.
This means the following parameters:

-     **origin** of the coordinate system (can be changed via "place coordinate system" in the GUI)
-     **visibility** of the coordinate system 
-     **size** of the coordinate system in the scene
-     **selected scale** 
-     **planet** (Mars, Earth, JPL etc.)

We can remove any or all of them from sequenced bookmarks, or show warnings. However, I would not recommend showing warnings for each of them, as that would be overwhelming. Looking at the list, my suggestion is:

-     **origin**  LEAVE IN WITHOUT WARNING
-     **visibility**  LEAVE IN WITHOUT WARNING
-     **size** LEAVE IN WITHOUT WARNING
-     **selected scale**  LEAVE IN WITHOUT WARNING
-     **planet** REMOVE


Other global settings that are currently saved with sequenced bookmarks are the following (in ViewConfigModel):
-   **nearPlane**             
-   **farPlane**              
-   **arrowLength**         
-   **arrowThickness**  
-   **dnsPlaneSize**      
-   **lodColoring**    
-   **drawOrientationCube** 

Should we remove any or all of these settings from sequenced bookmarks?

**Comment by RebeccaNowak** [comment]
@gpaar Please clarify which global settings should be removed or have warnings attached. Don't hesitate to ask if anything is unclear.

**Comment by gpaar** [comment]
With "coordinate system" I meant "Planet" anyway. So removing this from SB is fine.
Global settings that do not affect a specific drawing case shall be removed as well. 
nearPlane and FarPlane shall be kept in SB, as they affect the current drawing, same with all features of current drawings, such as dnsPlaneSize and drawOrientationCube. 
The global / default setting of various GUI parts shall not be affected by SBs. e.g. the default size of scale bars, or the default annotation color etc.
