### ISSUE TITLE
Flat views large zoom causes huge memory request

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#427]
Zooming in the frustrum causes huge memory requirements, more than 20GBytes causing 32GB system memory to get insufficient. Test data on sftp://provi-mastcam-z@dig-sftp.joanneum.at:2200/DataExchange/PRo3D-Testdata/Issues/427-2024-10-16-flat-view-SeqBookmarks-Memory - it contains a 1297a.pro3d file and the respective annotations and SB folder.
The launch of the sequenced bookmarks rendering stops on Frame 4, as the fulcrum gradually zooms in from 20 to 120 (which is not even the full resolution of Z110)
Also the interactive mode stalls after continuous memory devour if the state of SB "BB-Zoomed" is kept for some minutes. The view is ready in full resolution already after some seconds, but loading of invisible stuff into memory seems to continue in an uncontrolled manner thereafter.
![image](https://github.com/user-attachments/assets/1c708fbf-2540-4e13-bab1-e686a0ba34ef)

**Comment by haraldsteinlechner** [comment]
fixed/workaround in [PR](https://github.com/pro3d-space/PRo3D/pull/483).
I sketched a ray-guided lod scheme which works great but is unfortunately too expensive as implemented right now (not unsolvable but too dangerous to dig into right before important releases). The workaround as proposed in works reasonably well though https://github.com/pro3d-space/PRo3D/pull/483/commits/47292708bf08fb7dff557cc24ad3498dee3b8936.
