### ISSUE TITLE
OBJs disappearing when clicking play on sequenced bookmark sequence

### ISSUE THREAD

**Issue by RebeccaNowak** [pro3d-space/PRo3D#441]
- load an obj
- create some sequenced bokmarks
- click play
-> the surface disappears (from the surface list, not just visually)
- reload the surface
-> runtime error in Groups-Models.fs 

![image](https://github.com/user-attachments/assets/b633d604-61ed-4080-baf0-5f416238bf4a)

**Comment by LauraFritz14** [comment]
problem solved
