### ISSUE TITLE
Memory warning

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#468]
Pose a prominent warning when memory consumption on the system reaches 95%. This happens still very often and further memory need frequently results in system crash.
![20241127_103554_resized](https://github.com/user-attachments/assets/810ae78e-ce05-473b-81f7-d547038e41f2)

**Comment by haraldsteinlechner** [comment]
Was this related to "high" zoom levels? Also related: https://github.com/pro3d-space/PRo3D/issues/384

**Comment by gpaar** [comment]
Apparently, yet hadn't selected a narrow FoV. However, I had used HRC in the Viewplanner which DOES have a narrow FoV. It went slower and slower within the period of 2-3 minutes, and I didn't have an eye on the memory consumption before the system crashed. But other cases (with reportedly narrow FoV in the main window) went into the 95%+ memory usage before the system crashed, so I was assuming that the same happened here.
