### ISSUE TITLE
Mastcam-Z Improvements 

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#53]
Some small improvements are required for the Mastcam-Z project and should be available in the next release:

- [x] More digits in lat/long (change _stringformatter_).
- [x] Non spherical coordinate system (JPL and none) have no "North", show only "xyz" as labels for axes in 3D scene.
- [x] Check labels for reference system visualisation.    
- [x] Change height (along sky-vector) via keystroke in free-fly mode, - use SHIFT+W/S for up and down.
- [x] Numeric entry next to colour sliders (GUI element configuration)
- [x] Scalebar integration (issue #10)
- [x] Focal length integration (issue #54)
- [x] Move the "actions" tab down to the bottom bar in the UI

Requirements: [P3D-N002](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=31:31), [P3D-V001](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=28:28) and Discord/#releases

**Comment by LauraFritz14** [comment]
Branch: develop/features/mastcamZ1
Commit c83f4ea

**Comment by chris-traxler** [comment]
The test of the features checked above was successful and everything works perfectly. Only the scalebars are not integrated into this branch. This should probably be considered for the next pre-release.
Concerning the point "Change height", we decided to extend the basic camera control (@krauthaufen will look at that).

**Comment by gpaar** [comment]
Deprecated / redundant to more recent entries
