### ISSUE TITLE
Adjust Focal Length

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#54]
The focal length of the render camera should be adjustable in the GUI. This should work in the same way as for the instrument camera in the View Planner. Task separation:

- [x] Numerical field in GUI in the range of 28-100mm.
- [ ] Fix the horizontal field of view in the render window (Martin Brunnhuber has solved this for the Dibit-Viewer).

**Comment by LauraFritz14** [comment]
**Branch**: develop/features/mastcamZ1
Commit c83f4ea

![focalGui](https://user-images.githubusercontent.com/24911426/118484329-6285d180-b717-11eb-9f00-54a379572046.png)

**Comment by chris-traxler** [comment]
Changing the focal length works smoothly. There is just one small usability issue: When activating "useFocal" immediately after PRo3D was launched, it has no effect on the render window. The slider has to be moved first or the input field edited to see an effect.

**Comment by LauraFritz14** [comment]
Commit 7761d6e
init focal view with frustum using already init focal length

**Comment by chris-traxler** [comment]
Usability issue described above is fixed with commit https://github.com/vrvis/PRo3D/commit/7761d6e258a9f14c17c64fc29f915918c04250c8.

**Comment by gpaar** [comment]
Redundant
