### ISSUE TITLE
Given annotation group names not shown in UI

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#83]
When creating a new annotation group and changing its name, the name in the properties tab is always “newGroup” instead of the given name. It works after saving and reloading the scene. 
Remark: This bug does not affect the bookmark groups.

https://user-images.githubusercontent.com/5574563/127992381-c64ff701-e32d-4b9f-b21e-96d5541562f3.mp4

**Comment by RebeccaNowak** [comment]
Likely cause is in Bookmarks.fs: Using AVal.force on group name
(BookmarkAction.GroupsMessage(GroupsAppAction.SetActiveGroup (group.key |> AVal.force, path, group.name |> AVal.force)))

**Comment by RebeccaNowak** [comment]
Confirmed cause, bug exists for annotations, surfaces, and bookmarks.
