### ISSUE TITLE
4.0.0 crashes upon dll load

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#87]
![CooTrafo-Load-Crash](https://user-images.githubusercontent.com/65888251/128860554-2f415eb8-f51f-4868-8d4e-bf61b9f6802e.JPG)

**Comment by haraldsteinlechner** [comment]
thanks for automated testing ;) - we did not pass all testing machines for the prerelease yet - interesting this happens though. also another just reported the problem.
