### ISSUE TITLE
Editing Properties of single or multiple items

### ISSUE THREAD

**Issue by ThomasOrtner** [pro3d-space/PRo3D#9]
Change properties of single and multiple items, while current items are **annotations**, **surfaces**, and **bookmarks**. In case of annotations we want to change line width, color, or text labels. The property controls in the GUI and measurement results should be visible at the same time as the grouping tree structure, like in a drawing application. 

Only one type of item can be selected simultaneously, consequently selecting a different item type, single or multi, deselects the previously selected item(s). When multiple items are selected, properties change into a "bulk change" control, changes need to be confirmed with an "Apply" button.

- [x] annotation properties into separate tab
- [ ] generic properties tab for all items
- [ ] selections global (single and multi)
- [ ] "bulk change" properties when multiple items are selected
- [ ] Add attribute to each annotation - annotation should know which group it belongs to

[Requirement P3D-M006](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=8:8) & [P3D-E011](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=74:74)

**Comment by gpaar** [comment]
Taken over to https://github.com/pro3d-space/PRo3D/issues/249
